ALTER TABLE projects
ADD COLUMN report_deadline DATETIME DEFAULT NULL,
ADD COLUMN supervisor_score DECIMAL(4,2) DEFAULT NULL,
ADD COLUMN reviewer_score DECIMAL(4,2) DEFAULT NULL,
ADD COLUMN council_score DECIMAL(4,2) DEFAULT NULL,
ADD COLUMN final_score DECIMAL(4,2) DEFAULT NULL,
ADD COLUMN grade VARCHAR(10) DEFAULT NULL;
